JMB-18 Enhancements - Emergency Section Improvements
hsivritepe/jamb-frontend pull request #10
Opened 2024-12-18 05:36 UTC by karpushok

This pull request completes all the pages within the Emergency section and implements session storage to enhance user experience.

**Key Changes:**
	1.	Completed All Emergency Pages:
	•	Finalized the structure, design, and functionality for all pages in the Emergency section.
	•	Ensured proper navigation between pages.
	2.	Session Storage Integration:
	•	Added session storage to preserve user input and selections across pages.
	•	Implemented recovery of session data to ensure a seamless experience when users navigate back or refresh the page.
	3.	Data Transfer Improvements:
	•	All user-entered data, including services, descriptions, uploaded photos, and selected dates, are correctly passed from the Estimate page to the Checkout page.
	•	Steps and service details are now displayed accurately, ensuring consistency with the previous pages.
	4.	Bug Fixes:
	•	Resolved issues with incorrect steps being displayed on the Checkout page.
	•	Fixed calculation errors for the estimate total.
	
**Testing:**
	•	Verified session storage functionality for all user inputs.
	•	Tested navigation between Estimate → Checkout pages.
	•	Confirmed that data is restored correctly on page reload.
	•	Ensured calculations and service steps display accurately.
	
**How to Test:**
	1.	Navigate through the Emergency section pages.
	2.	Input data (services, photos, description, date) on the Estimate page.
	3.	Proceed to the Checkout page and verify:
	•	All input data (services, photos, description, date) is displayed correctly.
	•	The estimate total is calculated accurately.
	•	Emergency steps are rendered as per selected services.
	4.	Refresh the page and confirm that session data is retained.
	
**Jira Ticket:** JMB-18
**Status:** ### Complete

2024-12-20 02:01 UTC, hsivritepe requested changes
Hi Andrei,
I checked the files and they look good but when you check the request, you will see that it is throwing some errors. Please check those errors and try to make the adjustment. Let me know if you need help so I can get in and take a deeper look.

2024-12-20 05:58 UTC, karpushok commented
Hi Hakan,

I’m unable to log in to Vercel to check the problem. It’s not working with my GitHub or even my email.
Could you please make the necessary changes and accept the PR?

Thank you!

2025-01-14 13:49 UTC, hsivritepe approved these changes

2025-01-14 13:54 UTC, hsivritepe approved these changes

2025-01-14 13:54 UTC, merged